### PR TITLE
Add Image Optimisation strategy

### PR DESCRIPTION
**Pull request by kyranb**
As discussed here: https://github.com/czim/laravel-paperclip/issues/24#issuecomment-414986121

This uses https://github.com/spatie/image-optimizer/ behind the scenes to take care of image optimisation. 

Right now it's just using Spatie's defaults, but it could be extended to accept optimisation options as well.

### CODE REVIEW

**Comment by czim** [comment]
Had a chance to check this, and it's looking good. If you can find the time to add test(s) for this strategy, that would be great!

**Comment by kyranb** [comment]
Thanks Conrad. Sure thing :)

Oh and as for the method naming, the arrGet method was consistent with the
other Image Support classes, I'm not sure if you want to update them there
to reflect things as well.

**Comment by czim** [comment]
My bad, then -- looks like I will need to update those too. Good catch :]

**Comment by kyranb** [comment]
Sorry for leaving you hanging on this one. I've just followed the same testing style as the others, it doesn't exactly assert that the image has been optimised, but it asserts that the class does perform the function on the same file.

**Comment by kyranb** [comment]
Any chance of getting this merged in?

**Comment by czim** [comment]
I got caught up in other stuff. Can you rebase this? I'll merge it in right after. Thanks!

**Pull request merged**
